# Generated by Django 4.0.6 on 2022-08-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='goodsModel',
            new_name='goodesModel',
        ),
    ]
