# Generated by Django 4.0.6 on 2022-08-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goodesmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodesmodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='imagesGoodes'),
        ),
    ]
