# Generated by Django 4.0.6 on 2022-08-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_rename_img_goodesmodel_imagegoodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodesmodel',
            name='imageGoodes',
            field=models.ImageField(upload_to='imagesGoodes'),
        ),
    ]
