# Generated by Django 4.0.6 on 2022-08-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_ordersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='goodesCountFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormCountCol', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ordersModel',
        ),
    ]
